<?php


return [
    'admins' => [
        'name' => 'admins',
        'model' => \App\Models\Admin::class,
        'columns' => [
            'id' => 'id',
            'first_name' => 'first_name',
            'last_name' => 'last_name',
            'photo' => 'photo',
            'birthday' => 'birthday',
            'gender' => 'gender',
            'phone_number' => 'phone_number',
            'email' => 'email',
            'description' => 'description',
            'job' => 'job',
            'role' => 'role',
            'status' => 'status',
            'created_at' => 'created_at',
            'created_by' => 'created_by',
            'updated_by' => 'updated_by',
            'password' => 'password',
            'token' => 'token',
            'token_create_at' => 'token_create_at',
            'last_seen' => 'last_seen',
            'remember_token' => 'remember_token',
        ]
    ],
    'abonnements' => [
        'name' => 'abonnements',
        'model' => \App\Models\Abonnement::class,
        'columns' => [
            'id' => 'id',
            'title' => 'title_abonnement',
            'description' => 'description',
            'number_accounts_anseignants' => 'number_accounts_enseignants',
            'number_accounts_scolarite' => 'number_accounts_scolarite',
            'tarif_vente' => 'tarif_vente',
            'tarif_promo' => 'tarif_promo',
        ],
    ],
    'centreformationsabonnement' => [
        'name' => 'centreformationsabonnement',
        'model' => \App\Models\CentreFormationAbonnement::class,
        'columns' => [
            'id' => 'id',
            'abonnement_Fk' => 'abonnement_fk',
            'admin_FK' => 'admin_fk',
            'center_FK' => 'center_fk',
            'date_end' => 'date_end',
            'date_start' => 'date_start',
            'state' => 'state',
        ],
    ],
    'directeure' => [
        'name' => 'directeure',
        'model' => \App\Models\Directeure::class,
        'columns' => [
            'id' => 'id',
            'cin' => 'cin',
            'first_name' => 'first_name',
            'last_name' => 'last_name',
            'gender' => 'gender',
            'civility' => 'civility',
            'date_of_birth' => 'date_of_birth',
            'title_function' => 'title_function',
            'type' => 'type',
            'avatar' => 'avatar',
            'date_creation' => 'date_creation',
            'date_modification' => 'date_modification',
            'user_change' => 'user_change',
            'observation' => 'observation',
            'phone' => 'phone',
            'fax' => 'fax',
            'gsm' => 'gsm',
            'web_site' => 'web_site',
            'email' => 'email',
            'address' => 'address',
            'city' => 'city',
            'postal_code' => 'postal_code',
            'nationality' => 'nationality',
            'country' => 'country',
        ],
    ],
    'etablissements' => [
        'name' => 'etablissements',
        'model' => \App\Models\Etablissement::class,
        'columns' => [
            'id' => 'id',
            'name_AR' => 'name_AR',
            'name_FR' => 'name_FR',
            'address' => 'address',
            'city' => 'city',
            'postal_code' => 'postal_code',
            'country' => 'country',
            'email' => 'email',
            'web_site' => 'web_site',
            'phone' => 'phone',
            'whatsapp' => 'whatsapp',
            'logo' => 'logo',
            'description_FR' => 'description_FR',
            'description_AR' => 'description_AR',
            'directeur_FK' => 'directeur_fk',
        ],
    ],
    'centreformations' => [
        'name' => 'centreformations',
        'model' => \App\Models\CentreFormation::class,
        'columns' => [
            'id' => 'id',
            'etablissement_FK' => 'etablissement_fk',
            'name_AR' => 'name_AR',
            'name_FR' => 'name_FR',
            'address' => 'address',
            'city' => 'city',
            'postal_code' => 'postal_code',
            'country' => 'country',
            'email' => 'email',
            'web_site' => 'web_site',
            'phone' => 'phone',
            'whatsapp' => 'whatsapp',
            'logo' => 'logo',
            'description_FR' => 'description_FR',
            'description_AR' => 'description_AR',
        ],
    ],
    'collaborateurs' => [
        'name' => 'collaborateurs',
        'model' => \App\Models\Collaborateur::class,
        'columns' => [
            'id' => 'id',
            'matricule' => 'matricule',
            'cin' => 'cin',
            'first_name' => 'first_name',
            'last_name' => 'last_name',
            'birthday' => 'birthday',
            'gender' => 'gender',
            'civility' => 'civility',
            'fonction' => 'fonction',
            'avatar' => 'avatar',
            'phone_number' => 'phone_number',
            'email' => 'email',
            'city' => 'city',
            'postal_code' => 'postal_code',
            'address' => 'address',
            'observation' => 'observation',
            'category' => 'category',
            'nature_contrat' => 'nature_contrat',
            'center_FK' => 'center_fk',
        ],
    ],
    'office' => [
        'name' => 'office',
        'model' => \App\Models\OfficeAccount::class,
        'columns' => [
            'id' => 'id',
            'centreformabon_FK' => 'centreformabon_fk',
            'etablissement_FK' => 'etablissement_fk',
            'collaborateur_FK' => 'collaborateur_fk',
            'last_seen' => 'last_seen',
            'status' => 'status',
            'role' => 'role',
            'login' => 'login',
            'date_creation' => 'date_creation',
            'date_last_update' => 'date_last_update',
            'password' => 'password',
            'code_generate' => 'code_generate',
            'gendered_time' => 'gendered_time',
            'last_password_change' => 'last_password_change',
            'original_password' => 'original_password',
            'is_connected' => 'is_connected',
            'token' => 'token',
            'token_created_at' => 'token_created_at',
        ],
    ],
    'secteurs' => [
        'name' => 'secteurs',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
        ],
    ],
    'options' => [
        'name' => 'options',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'fk_secteur' => 'secteur',
            'fk_etablissement' => 'etablissement',
            'code' => 'code',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
        ],
    ],
    'filieres' => [
        'name' => 'filliereniveau',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'code' => 'code',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'niveau' => 'niveau',
            'diplome_fr' => 'diplome_fr',
            'diplome_ar' => 'diplome_ar',
            'conditions_ad_fr' => 'conditions_ad_fr',
            'conditions_ad_ar' => 'conditions_ad_ar',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
            'fk_options' => 'option',
        ],
    ],
    'etablissement_options' => [
        'name' => 'etablissement_options',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'fk_centreformations' => 'centre_formation',
            'fk_options' => 'option',
        ],
    ],
    'periodes' => [
        'name' => 'periodess',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'code' => 'code',
            'fk_filieres' => 'filiere',
            'name' => 'name',
            'start_date' => 'start_date',
            'end_date' => 'end_date',
            'description' => 'description',
        ],
    ],
    'modules' => [
        'name' => 'moduless',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'code' => 'code',
            'fk_options' => 'option',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'duration' => 'duration',
            'coefficient' => 'coefficient',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
        ],
    ],
    'matieres' => [
        'name' => 'matieress',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'code' => 'code',
            'fk_modules' => 'module',
            'fk_periodes' => 'periode',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'duration' => 'duration',
            'coefficient' => 'coefficient',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
        ],
    ],
    'chapitres' => [
        'name' => 'chapitress',
        'model' => null,
        'columns' => [
            'fk_matieres' => 'matiere',
            'id' => 'id',
            'reference' => 'reference',
            'name_fr' => 'name_fr',
            'name_ar' => 'name_ar',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',

        ],
    ],
    'chapitre_details' => [
        'name' => 'chapitre_detailss',
        'model' => null,
        'columns' => [
            'id' => 'id',
            'code' => 'code',
            'fk_chapitres' => 'chapitre',
            'title_fr' => 'title_fr',
            'title_ar' => 'title_ar',
            'description_fr' => 'description_fr',
            'description_ar' => 'description_ar',
        ],
    ],


];

